openapi: 3.0.2
info:
  title: MoldON API V1
  version: 1.0.0
  description: |-
    3D도면 바운딩 박스 추출
    - 3D도면을 업로드하여 3D도면의 바운딩박스 값을 추출하는 기능입니다.
  x-logo: 
    url: 'https://myeonggwon.github.io/GetAllWords/MoldON_logo.png'
    altText: A Logo image of MoldON
paths:
  /Boundbox:
    post:
      summary: Boundbox
      tags:
        - 3D도면 바운딩 박스 추출
      description: >-
        3D 도면 바운딩 박스 추출
      parameters: 
        - in: formData
          name: file_3d
          type: file
          description: The 3d file to upload.
      security:
        - APIKeyAuth: []
      responses:
        '200':
          description: successfully authenticated
          content:
            application/json:
              example:
                file_name: "~/p_0b0c4a17-f7f6-45c5-867e-58db7e2ce2cb_1.igs"
                boundBoxLX: 125.1
                boundBoxLY: 125.1
                boundBoxLZ: 125.1
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response_Boundbox'
        '201':
          description: Undocumented
          content:
            application/json:
              example:
                error: Undocumented
                status: 201
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: unauthorized
                status: 401
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody_Bbox'
servers:
  - url: http://ec2-52-79-123-200.ap-northeast-2.compute.amazonaws.com:8090/v1
    description: Production server
security:
  - APIKeyAuth: []
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: x-mold-apigw-api-key
      in: header
  schemas:
    Response_Boundbox:
      description: Respresentation of all words response.
      type: object
      properties:
        file_name:
          description: 3D file 명
          type: string
        boundBoxLX:
          description: X값 크기
          type: float
        boundBoxLY:
          description: Y값 크기
          type: float
        boundBoxLZ:
          description: Z값 크기
          type: float
    RequestBody_Bbox:
      description: Request file-name and file
      required: ["file_name", "file_3d"]
      type: object
      properties:
        file_name:
          type: string
          description: 3D file 경로
          example: "~/p_0b0c4a17-f7f6-45c5-867e-58db7e2ce2cb_1.igs"
        file_3d:
          type: file
          format: binary
          description: 실제 3D file(* stp, igs 파일만 가능)