openapi: 3.0.2
info:
  title: MoldON API V1
  version: 1.0.0
  description: |-
    3D도면 바운딩 박스 추출
    - 3D도면을 업로드하여 3D도면의 바운딩박스 값을 추출하는 기능입니다.
  x-logo: 
    url: 'https://moldmecca.github.io/GetAllWords/MoldON_logo.png'
    altText: A Logo image of MoldON
paths:
  /Boundbox:
    post:
      summary: Boundbox
      tags:
        - 3D도면 바운딩 박스 추출
      description: >-
        3D 도면 바운딩 박스 추출
      parameters: 
        - in: formData
          name: file_3d
          type: file
          description: The 3d file to upload.
      security:
        - APIKeyAuth: []
      responses:
        '200':
          description: successfully authenticated
          content:
            application/json:
              example:
                file_name: p_00c3c92e-a550-4df2-8e15-5758a750b1ef_1.stp
                tmp_file_name: 46fd832c-ddcb-4732-aad3-3776cc793bba.stp
                boundBoxLX: 1128.116
                boundBoxLY: 81.733
                boundBoxLZ: 326.551
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response_Boundbox'
        '201':
          description: igs or stp 파일이 아닌 경우
          content:
            application/json:
              example:
                detail : "Error : Only igs or stp files are supported." 
        '401':
          description: 바운딩 박스 값 추출 오류
          content:
            application/json:
              example:
                detail : " Error : error message"
        '403':
          description: API KEY 오류
          content:
            application/json:
              example:
                detail: "The API-key is invalid.. or The API-key has expired.." 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody_Bbox'
servers:
  - url: https://api.moldon.org/v1
    description: Production server
security:
  - APIKeyAuth: []
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: x-mold-apigw-api-key
      in: header
  schemas:
    Response_Boundbox:
      description: Respresentation of all words response.
      type: object
      properties:
        file_name:
          description: 3D file 명
          type: string
        tmp_file_name:
          description: 서버에 저장되는 임시 파일 명
          type: string
        boundBoxLX:
          description: X값 크기
          type: float
        boundBoxLY:
          description: Y값 크기
          type: float
        boundBoxLZ:
          description: Z값 크기
          type: float
    RequestBody_Bbox:
      description: Request file-name and file
      required: ["file_3d"]
      type: object
      properties:
        file_3d:
          type: file
          format: binary
          description: 실제 도면 파일(**stp, igs 파일만 가능**)